apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "powerjob.mysql.fullname" . }}
  labels:
    app.kubernetes.io/component: mysql
    {{- include "powerjob.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: mysql
      {{- include "powerjob.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: mysql
        {{- include "powerjob.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          args:
            {{- toYaml .Values.mysql.commandArgs | nindent 12 }}
          env:
            - name: MYSQL_ROOT_HOST
              value: "%"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "powerjob.mysql.fullname" . }}-secret
                  key: mysql-root-password
          ports:
            - containerPort: {{ .Values.mysql.port }}
              name: mysql
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          resources:
            {{- toYaml .Values.mysql.resources | nindent 12 }}
      volumes:
        - name: data
          {{- if .Values.mysql.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "powerjob.mysql.fullname" . }}-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
