apiVersion: v1
kind: Service
metadata:
  name: {{ include "powerjob.mysql.fullname" . }}
  labels:
    {{- include "powerjob.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mysql.port }}
      targetPort: {{ .Values.mysql.port }}
      protocol: TCP
      name: mysql
  selector:
    app.kubernetes.io/component: mysql
    {{- include "powerjob.selectorLabels" . | nindent 4 }}
