apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "powerjob.server.fullname" . }}
  labels:
    app.kubernetes.io/component: server
    {{- include "powerjob.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      {{- include "powerjob.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: server
        {{- include "powerjob.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-mysql
          image: {{ .Values.initContainer.image }}
          imagePullPolicy: {{ .Values.initContainer.imagePullPolicy }}
          command:
            - sh
            - -c
            - |
              until nc -z {{ include "powerjob.mysql.fullname" . }} {{ .Values.mysql.port }}; do
                echo "Waiting for MySQL..."
                sleep 2
              done
              echo "MySQL is ready"
      containers:
        - name: server
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          env:
            - name: JVMOPTIONS
              value: {{ .Values.server.env.JVMOPTIONS | quote }}
            - name: PARAMS
              value: "--oms.mongodb.enable=false --spring.datasource.core.jdbc-url=jdbc:mysql://{{ include "powerjob.mysql.fullname" . }}:{{ .Values.mysql.port }}/{{ .Values.mysql.database }}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&user={{ .Values.mysql.auth.username }}&password={{ .Values.mysql.auth.password }}"
          ports:
            {{- range .Values.server.ports }}
            - containerPort: {{ .containerPort }}
              name: {{ .name }}
            {{- end }}
          volumeMounts:
            - name: data
              mountPath: /root/powerjob/server/
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
      volumes:
        - name: data
          {{- if .Values.server.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "powerjob.server.fullname" . }}-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
