apiVersion: v1
kind: Service
metadata:
  name: {{ include "powerjob.worker.fullname" . }}
  labels:
    app.kubernetes.io/component: worker
    {{- include "powerjob.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    {{- range .Values.worker.ports }}
    - port: {{ .servicePort }}
      targetPort: {{ .containerPort }}
      protocol: TCP
      name: {{ .name }}
    {{- end }}
  selector:
    app.kubernetes.io/component: worker
    {{- include "powerjob.selectorLabels" . | nindent 4 }}
